### ISSUE TITLE
About the detail of automatical calibration using camera feedback in the post-fabrication stage

### ISSUE THREAD

**Issue by fkmajiji** [computational-imaging/holographic-AR-glasses#1]
Hello, this work is great! I am very interested in automatical calibration using camera feedback in the post-fabrication stage. Do you know where I can find more implement details in paper or code?

**Comment by manugopa** [comment]
This code base includes the model that we used for the calibration. To create and capture the dataset to train this model, we used a procedure similar to the one outlined at [this repo of our previous neural 3D holography paper](https://github.com/computational-imaging/neural-3d-holography/tree/main). The capturing and alignment code may have to be adapted based on the specific camera hardware that you use.
