### ISSUE TITLE
Code of optimization of the geometry of the metasurface gratings.

### ISSUE THREAD

**Issue by shu0x0y** [computational-imaging/holographic-AR-glasses#2]
Hello, this work is great! I am very interested in optimization of the geometry of the metasurface gratings. It seems that there is no code of it in this repository. is it unavailable or did I not find? Do you know where I can find it in paper or code?

**Comment by gunyeal** [comment]
Thanks for your interest! We have not uploaded the optimization code for this project here, but you could start the optimization work by referring to these public rcwa repositories: [grcwa](https://github.com/weiliangjinca/grcwa), [torcwa](https://github.com/kch3782/torcwa)

You can also find details about the optimization conditions in the manuscript and supplementary materials.
